# Generated by Django 4.0.1 on 2022-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_apellidos_alter_autor_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
