# Generated by Django 4.0.1 on 2022-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha de debolución'),
        ),
    ]
