# Generated by Django 4.0.1 on 2022-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
    ]
