# Generated by Django 4.0.1 on 2022-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_alter_lector_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
