# Generated by Django 4.0.1 on 2022-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0005_alter_lector_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de devolución'),
        ),
    ]
